In [40]:
data = open("Desktop\customerdata.txt",'r')
data = data.readlines()
ctmdata = []
for line in data:
    temp = []
    for eles in line.split():
        temp.append(eles[:-1])
    ctmdata.append(temp)    
ctmdata

[['Date', 'Phone', 'Name', 'Amoun'],
 ['2016-04-29', '9455622241', 'Shankar', 'Narasimhan', '26'],
 ['2016-04-29', '9597628723', 'Suly', 'Gupta', '9'],
 ['2016-04-29', '9640338121', 'Brahm', 'Swamy', '8'],
 ['2016-04-29', '9383568793', 'Vaibha', 'Mulye', '24'],
 ['2016-04-29', '9455622241', 'Shankar', 'Narasimhan', '23'],
 ['2016-04-29', '9521737322', 'Riddh', 'Nair', '7'],
 ['2016-04-29', '9389644210', 'Brahm', 'Swamy', '8'],
 ['2016-04-29', '9603660688', 'Dhenuk', 'Dhawan', '25'],
 ['2016-04-29', '9451926724', 'Saha', 'Sibal', '26'],
 ['2016-04-29', '9699939066', 'Haripriy', 'Nayak', '27'],
 ['2016-04-29', '9590146908', 'Sach', 'Loliyekar', '11'],
 ['2016-04-29', '9389644210', 'Brahm', 'Swamy', '10'],
 ['2016-04-29', '9640338121', 'Brahm', 'Swamy', '24'],
 ['2016-04-29', '9236367267', 'Takshak', 'Sandal', '7'],
 ['2016-04-30', '9969345730', 'Kav', 'Edwin', '21'],
 ['2016-04-30', '9389644210', 'Brahm', 'Swamy', '28'],
 ['2016-04-30', '9971276037', 'Pramloch', 'Comar', '21'],
 ['2016-04-30', '9241664018', 'Utathy', 'Ghate', '26'],
 ['2016-04-30', '9248936762', 'Arpan', 'Raja', '26'],
 ['2016-04-30', '9640338121', 'Brahm', 'Swamy', '20'],
 ['2016-04-30', '9895408016', 'Muku', 'Krishna', '18'],
 ['2016-04-30', '9241664018', 'Utathy', 'Ghate', '26'],
 ['2016-04-30', '9920950009', 'Roha', 'Sarma', '11'],
 ['2016-04-30', '9820224845', 'Tanik', 'Philip', '9'],
 ['2016-04-30', '9383568793', 'Vaibha', 'Mulye', '20'],
 ['2016-04-30', '9732082404', 'Kal', 'Chaudry', '29'],
 ['2016-04-30', '9534474777', 'Daev', 'Tata', '7'],
 ['2016-05-01', '9389644210', 'Brahm', 'Swamy', '16'],
 ['2016-05-01', '9572464275', 'Salmali', 'Mehta', '10'],
 ['2016-05-01', '9688156631', 'Saha', 'Oak', '20'],
 ['2016-05-01', '9236367267', 'Takshak', 'Sandal', '25'],
 ['2016-05-01', '9979209995', 'Atma', 'Mathur', '14'],
 ['2016-05-01', '9521737322', 'Riddh', 'Nair', '14'],
 ['2016-05-01', '9265205814', 'Daev', 'Peri', '18'],
 ['2016-05-01', '9267357082', 'Mun', 'Wasgare', '21'],
 ['2016-05-01', '9267357082', 'Mun', 'Wasgare', '29'],
 ['2016-05-01', '9590146908', 'Sach', 'Loliyekar', '19'],
 ['2016-05-01', '9389644210', 'Brahm', 'Swamy', '29'],
 ['2016-05-01', '9241664018', 'Utathy', 'Ghate', '18'],
 ['2016-05-02', '9971276037', 'Pramloch', 'Comar', '8'],
 ['2016-05-02', '9920950009', 'Roha', 'Sarma', '14'],
 ['2016-05-02', '9705384480', 'Lati', 'Chia', '7'],
 ['2016-05-02', '9252350612', 'Anushk', 'Mody', '15'],
 ['2016-05-02', '9688156631', 'Saha', 'Oak', '29'],
 ['2016-05-02', '9359394987', 'Taru', 'Mapkar', '26'],
 ['2016-05-02', '9747425720', 'Markandey', 'Barad', '10'],
 ['2016-05-02', '9389644210', 'Brahm', 'Swamy', '18'],
 ['2016-05-02', '9699939066', 'Haripriy', 'Nayak', '11'],
 ['2016-05-02', '9590146908', 'Sach', 'Loliyekar', '22'],
 ['2016-05-02', '9820224845', 'Tanik', 'Philip', '22'],
 ['2016-05-02', '9747425720', 'Markandey', 'Barad', '9'],
 ['2016-05-03', '9910042819', 'Shant', 'Bajwa', '10'],
 ['2016-05-03', '9518195948', 'Indr', 'Chaudry', '11'],
 ['2016-05-03', '9389644210', 'Brahm', 'Swamy', '8'],
 ['2016-05-03', '9236367267', 'Takshak', 'Sandal', '10'],
 ['2016-05-03', '9640338121', 'Brahm', 'Swamy', '10'],
 ['2016-05-03', '9389644210', 'Brahm', 'Swamy', '12'],
 ['2016-05-03', '9453085874', 'Man', 'Oza', '12'],
 ['2016-05-03', '9976945538', 'Amitabh', 'Kothari', '27'],
 ['2016-05-03', '9910042819', 'Shant', 'Bajwa', '28'],
 ['2016-05-03', '9389644210', 'Brahm', 'Swamy', '20'],
 ['2016-05-03', '9405883814', 'Gaur', 'Som', '22'],
 ['2016-05-03', '9252350612', 'Anushk', 'Mody', '17'],
 ['2016-05-04', '9453085874', 'Man', 'Oza', '12'],
 ['2016-05-04', '9640338121', 'Brahm', 'Swamy', '15'],
 ['2016-05-04', '9927277067', 'Ranja', 'Khare', '8'],
 ['2016-05-04', '9910042819', 'Shant', 'Bajwa', '25'],
 ['2016-05-04', '9389644210', 'Brahm', 'Swamy', '20'],
 ['2016-05-04', '9293117791', 'Kumar', 'Nayak', '25'],
 ['2016-05-04', '9976945538', 'Amitabh', 'Kothari', '11'],
 ['2016-05-04', '9518195948', 'Indr', 'Chaudry', '20'],
 ['2016-05-04', '9518195948', 'Indr', 'Chaudry', '13'],
 ['2016-05-04', '9389644210', 'Brahm', 'Swamy', '14'],
 ['2016-05-04', '9521737322', 'Riddh', 'Nair', '12'],
 ['2016-05-04', '9920950009', 'Roha', 'Sarma', '12'],
 ['2016-05-04', '9597628723', 'Suly', 'Gupta', '14'],
 ['2016-05-04', '9534474777', 'Daev', 'Tata', '7'],
 ['2016-05-04', '9009381182', 'Mir', 'Reddy', '24'],
 ['2016-05-04', '9009381182', 'Mir', 'Reddy', '16'],
 ['2016-05-04', '9236367267', 'Takshak', 'Sandal', '15'],
 ['2016-05-04', '9265205814', 'Daev', 'Peri', '18'],
 ['2016-05-05', '9451926724', 'Saha', 'Sibal', '17'],
 ['2016-05-05', '9504662177', 'Tar', 'Menon', '23'],
 ['2016-05-05', '9455622241', 'Shankar', 'Narasimhan', '20'],
 ['2016-05-05', '9927277067', 'Ranja', 'Khare', '11'],
 ['2016-05-05', '9521737322', 'Riddh', 'Nair', '9'],
 ['2016-05-05', '9252350612', 'Anushk', 'Mody', '12'],
 ['2016-05-05', '9699939066', 'Haripriy', 'Nayak', '7'],
 ['2016-05-05', '9150159527', 'Ley', 'Sankaran', '27'],
 ['2016-05-05', '9389644210', 'Brahm', 'Swamy', '24'],
 ['2016-05-05', '9733555024', 'Nira', 'Khalsa', '11'],
 ['2016-05-05', '9236367267', 'Takshak', 'Sandal', '20'],
 ['2016-05-05', '9241664018', 'Utathy', 'Ghate', '26'],
 ['2016-05-06', '9455622241', 'Shankar', 'Narasimhan', '21'],
 ['2016-05-06', '9389644210', 'Brahm', 'Swamy', '25'],
 ['2016-05-06', '9705384480', 'Lati', 'Chia', '16'],
 ['2016-05-06', '9359394987', 'Taru', 'Mapkar', '10'],
 ['2016-05-06', '9688156631', 'Saha', 'Oak', '21'],
 ['2016-05-06', '9688156631', 'Saha', 'Oak', '28'],
 ['2016-05-06', '9389644210', 'Brahm', 'Swamy', '11'],
 ['2016-05-06', '9699939066', 'Haripriy', 'Nayak', '13'],
 ['2016-05-06', '9389644210', 'Brahm', 'Swamy', '11'],
 ['2016-05-06', '9389644210', 'Brahm', 'Swamy', '9'],
 ['2016-05-06', '9597628723', 'Suly', 'Gupta', '19'],
 ['2016-05-06', '9521737322', 'Riddh', 'Nair', '14'],
 ['2016-05-06', '9451926724', 'Saha', 'Sibal', '23'],
 ['2016-05-06', '9403313898', 'Adr', 'Dave', '21'],
 ['2016-05-06', '9895408016', 'Muku', 'Krishna', '24'],
 ['2016-05-06', '9504662177', 'Tar', 'Menon', '14'],
 ['2016-05-07', '9389644210', 'Brahm', 'Swamy', '14'],
 ['2016-05-07', '9699939066', 'Haripriy', 'Nayak', '28'],
 ['2016-05-07', '9732082404', 'Kal', 'Chaudry', '13'],
 ['2016-05-07', '9150159527', 'Ley', 'Sankaran', '25'],
 ['2016-05-07', '9820224845', 'Tanik', 'Philip', '29'],
 ['2016-05-07', '9248936762', 'Arpan', 'Raja', '26'],
 ['2016-05-07', '9293117791', 'Kumar', 'Nayak', '20'],
 ['2016-05-07', '9640338121', 'Brahm', 'Swamy', '20'],
 ['2016-05-07', '9732082404', 'Kal', 'Chaudry', '28'],
 ['2016-05-07', '9265205814', 'Daev', 'Peri', '7'],
 ['2016-05-07', '9534474777', 'Daev', 'Tata', '16'],
 ['2016-05-07', '9252350612', 'Anushk', 'Mody', '8'],
 ['2016-05-07', '9389644210', 'Brahm', 'Swamy', '22'],
 ['2016-05-07', '9153022424', 'Hasti', 'Mangal', '18'],
 ['2016-05-07', '9920950009', 'Roha', 'Sarma', '16'],
 ['2016-05-07', '9534474777', 'Daev', 'Tata', '23'],
 ['2016-05-07', '9359394987', 'Taru', 'Mapkar', '26'],
 ['2016-05-07', '9969345730', 'Kav', 'Edwin', '10'],
 ['2016-05-08', '9389644210', 'Brahm', 'Swamy', '13'],
 ['2016-05-08', '9389644210', 'Brahm', 'Swamy', '12'],
 ['2016-05-08', '9504662177', 'Tar', 'Menon', '22'],
 ['2016-05-08', '9455622241', 'Shankar', 'Narasimhan', '15'],
 ['2016-05-08', '9389644210', 'Brahm', 'Swamy', '9'],
 ['2016-05-08', '9236367267', 'Takshak', 'Sandal', '11'],
 ['2016-05-08', '9330107696', 'Nip', 'Naidu', '7'],
 ['2016-05-08', '9927277067', 'Ranja', 'Khare', '18'],
 ['2016-05-08', '9140356318', 'Ballar', 'Upadhyay', '27'],
 ['2016-05-08', '9389644210', 'Brahm', 'Swamy', '7'],
 ['2016-05-08', '9518195948', 'Indr', 'Chaudry', '18'],
 ['2016-05-08', '9976945538', 'Amitabh', 'Kothari', '27'],
 ['2016-05-08', '9534474777', 'Daev', 'Tata', '21'],
 ['2016-05-08', '9504662177', 'Tar', 'Menon', '21'],
 ['2016-05-08', '9293117791', 'Kumar', 'Nayak', '20'],
 ['2016-05-08', '9293117791', 'Kumar', 'Nayak', '14'],
 ['2016-05-08', '9248936762', 'Arpan', 'Raja', '11'],
 ['2016-05-08', '9960294002', 'Mitr', 'Gounder', '24'],
 ['2016-05-08', '9150159527', 'Ley', 'Sankaran', '14'],
 ['2016-05-08', '9236367267', 'Takshak', 'Sandal', '25'],
 ['2016-05-09', '9732082404', 'Kal', 'Chaudry', '10'],
 ['2016-05-09', '9521737322', 'Riddh', 'Nair', '14'],
 ['2016-05-09', '9293117791', 'Kumar', 'Nayak', '19'],
 ['2016-05-09', '9590146908', 'Sach', 'Loliyekar', '15'],
 ['2016-05-09', '9688156631', 'Saha', 'Oak', '22'],
 ['2016-05-09', '9895408016', 'Muku', 'Krishna', '23'],
 ['2016-05-09', '9261697610', 'Niloufe', 'Handa', '13'],
 ['2016-05-09', '9927277067', 'Ranja', 'Khare', '17'],
 ['2016-05-09', '9640338121', 'Brahm', 'Swamy', '23'],
 ['2016-05-09', '9485132704', 'Sohali', 'Das', '25'],
 ['2016-05-09', '9330107696', 'Nip', 'Naidu', '24'],
 ['2016-05-09', '9389644210', 'Brahm', 'Swamy', '18'],
 ['2016-05-09', '9389644210', 'Brahm', 'Swamy', '21'],
 []]

In [42]:
ctmdata = ctmdata[1:-1]
ctmdata

[['2016-04-29', '9597628723', 'Suly', 'Gupta', '9'],
 ['2016-04-29', '9640338121', 'Brahm', 'Swamy', '8'],
 ['2016-04-29', '9383568793', 'Vaibha', 'Mulye', '24'],
 ['2016-04-29', '9455622241', 'Shankar', 'Narasimhan', '23'],
 ['2016-04-29', '9521737322', 'Riddh', 'Nair', '7'],
 ['2016-04-29', '9389644210', 'Brahm', 'Swamy', '8'],
 ['2016-04-29', '9603660688', 'Dhenuk', 'Dhawan', '25'],
 ['2016-04-29', '9451926724', 'Saha', 'Sibal', '26'],
 ['2016-04-29', '9699939066', 'Haripriy', 'Nayak', '27'],
 ['2016-04-29', '9590146908', 'Sach', 'Loliyekar', '11'],
 ['2016-04-29', '9389644210', 'Brahm', 'Swamy', '10'],
 ['2016-04-29', '9640338121', 'Brahm', 'Swamy', '24'],
 ['2016-04-29', '9236367267', 'Takshak', 'Sandal', '7'],
 ['2016-04-30', '9969345730', 'Kav', 'Edwin', '21'],
 ['2016-04-30', '9389644210', 'Brahm', 'Swamy', '28'],
 ['2016-04-30', '9971276037', 'Pramloch', 'Comar', '21'],
 ['2016-04-30', '9241664018', 'Utathy', 'Ghate', '26'],
 ['2016-04-30', '9248936762', 'Arpan', 'Raja', '26'],
 ['2016-04-30', '9640338121', 'Brahm', 'Swamy', '20'],
 ['2016-04-30', '9895408016', 'Muku', 'Krishna', '18'],
 ['2016-04-30', '9241664018', 'Utathy', 'Ghate', '26'],
 ['2016-04-30', '9920950009', 'Roha', 'Sarma', '11'],
 ['2016-04-30', '9820224845', 'Tanik', 'Philip', '9'],
 ['2016-04-30', '9383568793', 'Vaibha', 'Mulye', '20'],
 ['2016-04-30', '9732082404', 'Kal', 'Chaudry', '29'],
 ['2016-04-30', '9534474777', 'Daev', 'Tata', '7'],
 ['2016-05-01', '9389644210', 'Brahm', 'Swamy', '16'],
 ['2016-05-01', '9572464275', 'Salmali', 'Mehta', '10'],
 ['2016-05-01', '9688156631', 'Saha', 'Oak', '20'],
 ['2016-05-01', '9236367267', 'Takshak', 'Sandal', '25'],
 ['2016-05-01', '9979209995', 'Atma', 'Mathur', '14'],
 ['2016-05-01', '9521737322', 'Riddh', 'Nair', '14'],
 ['2016-05-01', '9265205814', 'Daev', 'Peri', '18'],
 ['2016-05-01', '9267357082', 'Mun', 'Wasgare', '21'],
 ['2016-05-01', '9267357082', 'Mun', 'Wasgare', '29'],
 ['2016-05-01', '9590146908', 'Sach', 'Loliyekar', '19'],
 ['2016-05-01', '9389644210', 'Brahm', 'Swamy', '29'],
 ['2016-05-01', '9241664018', 'Utathy', 'Ghate', '18'],
 ['2016-05-02', '9971276037', 'Pramloch', 'Comar', '8'],
 ['2016-05-02', '9920950009', 'Roha', 'Sarma', '14'],
 ['2016-05-02', '9705384480', 'Lati', 'Chia', '7'],
 ['2016-05-02', '9252350612', 'Anushk', 'Mody', '15'],
 ['2016-05-02', '9688156631', 'Saha', 'Oak', '29'],
 ['2016-05-02', '9359394987', 'Taru', 'Mapkar', '26'],
 ['2016-05-02', '9747425720', 'Markandey', 'Barad', '10'],
 ['2016-05-02', '9389644210', 'Brahm', 'Swamy', '18'],
 ['2016-05-02', '9699939066', 'Haripriy', 'Nayak', '11'],
 ['2016-05-02', '9590146908', 'Sach', 'Loliyekar', '22'],
 ['2016-05-02', '9820224845', 'Tanik', 'Philip', '22'],
 ['2016-05-02', '9747425720', 'Markandey', 'Barad', '9'],
 ['2016-05-03', '9910042819', 'Shant', 'Bajwa', '10'],
 ['2016-05-03', '9518195948', 'Indr', 'Chaudry', '11'],
 ['2016-05-03', '9389644210', 'Brahm', 'Swamy', '8'],
 ['2016-05-03', '9236367267', 'Takshak', 'Sandal', '10'],
 ['2016-05-03', '9640338121', 'Brahm', 'Swamy', '10'],
 ['2016-05-03', '9389644210', 'Brahm', 'Swamy', '12'],
 ['2016-05-03', '9453085874', 'Man', 'Oza', '12'],
 ['2016-05-03', '9976945538', 'Amitabh', 'Kothari', '27'],
 ['2016-05-03', '9910042819', 'Shant', 'Bajwa', '28'],
 ['2016-05-03', '9389644210', 'Brahm', 'Swamy', '20'],
 ['2016-05-03', '9405883814', 'Gaur', 'Som', '22'],
 ['2016-05-03', '9252350612', 'Anushk', 'Mody', '17'],
 ['2016-05-04', '9453085874', 'Man', 'Oza', '12'],
 ['2016-05-04', '9640338121', 'Brahm', 'Swamy', '15'],
 ['2016-05-04', '9927277067', 'Ranja', 'Khare', '8'],
 ['2016-05-04', '9910042819', 'Shant', 'Bajwa', '25'],
 ['2016-05-04', '9389644210', 'Brahm', 'Swamy', '20'],
 ['2016-05-04', '9293117791', 'Kumar', 'Nayak', '25'],
 ['2016-05-04', '9976945538', 'Amitabh', 'Kothari', '11'],
 ['2016-05-04', '9518195948', 'Indr', 'Chaudry', '20'],
 ['2016-05-04', '9518195948', 'Indr', 'Chaudry', '13'],
 ['2016-05-04', '9389644210', 'Brahm', 'Swamy', '14'],
 ['2016-05-04', '9521737322', 'Riddh', 'Nair', '12'],
 ['2016-05-04', '9920950009', 'Roha', 'Sarma', '12'],
 ['2016-05-04', '9597628723', 'Suly', 'Gupta', '14'],
 ['2016-05-04', '9534474777', 'Daev', 'Tata', '7'],
 ['2016-05-04', '9009381182', 'Mir', 'Reddy', '24'],
 ['2016-05-04', '9009381182', 'Mir', 'Reddy', '16'],
 ['2016-05-04', '9236367267', 'Takshak', 'Sandal', '15'],
 ['2016-05-04', '9265205814', 'Daev', 'Peri', '18'],
 ['2016-05-05', '9451926724', 'Saha', 'Sibal', '17'],
 ['2016-05-05', '9504662177', 'Tar', 'Menon', '23'],
 ['2016-05-05', '9455622241', 'Shankar', 'Narasimhan', '20'],
 ['2016-05-05', '9927277067', 'Ranja', 'Khare', '11'],
 ['2016-05-05', '9521737322', 'Riddh', 'Nair', '9'],
 ['2016-05-05', '9252350612', 'Anushk', 'Mody', '12'],
 ['2016-05-05', '9699939066', 'Haripriy', 'Nayak', '7'],
 ['2016-05-05', '9150159527', 'Ley', 'Sankaran', '27'],
 ['2016-05-05', '9389644210', 'Brahm', 'Swamy', '24'],
 ['2016-05-05', '9733555024', 'Nira', 'Khalsa', '11'],
 ['2016-05-05', '9236367267', 'Takshak', 'Sandal', '20'],
 ['2016-05-05', '9241664018', 'Utathy', 'Ghate', '26'],
 ['2016-05-06', '9455622241', 'Shankar', 'Narasimhan', '21'],
 ['2016-05-06', '9389644210', 'Brahm', 'Swamy', '25'],
 ['2016-05-06', '9705384480', 'Lati', 'Chia', '16'],
 ['2016-05-06', '9359394987', 'Taru', 'Mapkar', '10'],
 ['2016-05-06', '9688156631', 'Saha', 'Oak', '21'],
 ['2016-05-06', '9688156631', 'Saha', 'Oak', '28'],
 ['2016-05-06', '9389644210', 'Brahm', 'Swamy', '11'],
 ['2016-05-06', '9699939066', 'Haripriy', 'Nayak', '13'],
 ['2016-05-06', '9389644210', 'Brahm', 'Swamy', '11'],
 ['2016-05-06', '9389644210', 'Brahm', 'Swamy', '9'],
 ['2016-05-06', '9597628723', 'Suly', 'Gupta', '19'],
 ['2016-05-06', '9521737322', 'Riddh', 'Nair', '14'],
 ['2016-05-06', '9451926724', 'Saha', 'Sibal', '23'],
 ['2016-05-06', '9403313898', 'Adr', 'Dave', '21'],
 ['2016-05-06', '9895408016', 'Muku', 'Krishna', '24'],
 ['2016-05-06', '9504662177', 'Tar', 'Menon', '14'],
 ['2016-05-07', '9389644210', 'Brahm', 'Swamy', '14'],
 ['2016-05-07', '9699939066', 'Haripriy', 'Nayak', '28'],
 ['2016-05-07', '9732082404', 'Kal', 'Chaudry', '13'],
 ['2016-05-07', '9150159527', 'Ley', 'Sankaran', '25'],
 ['2016-05-07', '9820224845', 'Tanik', 'Philip', '29'],
 ['2016-05-07', '9248936762', 'Arpan', 'Raja', '26'],
 ['2016-05-07', '9293117791', 'Kumar', 'Nayak', '20'],
 ['2016-05-07', '9640338121', 'Brahm', 'Swamy', '20'],
 ['2016-05-07', '9732082404', 'Kal', 'Chaudry', '28'],
 ['2016-05-07', '9265205814', 'Daev', 'Peri', '7'],
 ['2016-05-07', '9534474777', 'Daev', 'Tata', '16'],
 ['2016-05-07', '9252350612', 'Anushk', 'Mody', '8'],
 ['2016-05-07', '9389644210', 'Brahm', 'Swamy', '22'],
 ['2016-05-07', '9153022424', 'Hasti', 'Mangal', '18'],
 ['2016-05-07', '9920950009', 'Roha', 'Sarma', '16'],
 ['2016-05-07', '9534474777', 'Daev', 'Tata', '23'],
 ['2016-05-07', '9359394987', 'Taru', 'Mapkar', '26'],
 ['2016-05-07', '9969345730', 'Kav', 'Edwin', '10'],
 ['2016-05-08', '9389644210', 'Brahm', 'Swamy', '13'],
 ['2016-05-08', '9389644210', 'Brahm', 'Swamy', '12'],
 ['2016-05-08', '9504662177', 'Tar', 'Menon', '22'],
 ['2016-05-08', '9455622241', 'Shankar', 'Narasimhan', '15'],
 ['2016-05-08', '9389644210', 'Brahm', 'Swamy', '9'],
 ['2016-05-08', '9236367267', 'Takshak', 'Sandal', '11'],
 ['2016-05-08', '9330107696', 'Nip', 'Naidu', '7'],
 ['2016-05-08', '9927277067', 'Ranja', 'Khare', '18'],
 ['2016-05-08', '9140356318', 'Ballar', 'Upadhyay', '27'],
 ['2016-05-08', '9389644210', 'Brahm', 'Swamy', '7'],
 ['2016-05-08', '9518195948', 'Indr', 'Chaudry', '18'],
 ['2016-05-08', '9976945538', 'Amitabh', 'Kothari', '27'],
 ['2016-05-08', '9534474777', 'Daev', 'Tata', '21'],
 ['2016-05-08', '9504662177', 'Tar', 'Menon', '21'],
 ['2016-05-08', '9293117791', 'Kumar', 'Nayak', '20'],
 ['2016-05-08', '9293117791', 'Kumar', 'Nayak', '14'],
 ['2016-05-08', '9248936762', 'Arpan', 'Raja', '11'],
 ['2016-05-08', '9960294002', 'Mitr', 'Gounder', '24'],
 ['2016-05-08', '9150159527', 'Ley', 'Sankaran', '14'],
 ['2016-05-08', '9236367267', 'Takshak', 'Sandal', '25'],
 ['2016-05-09', '9732082404', 'Kal', 'Chaudry', '10'],
 ['2016-05-09', '9521737322', 'Riddh', 'Nair', '14'],
 ['2016-05-09', '9293117791', 'Kumar', 'Nayak', '19'],
 ['2016-05-09', '9590146908', 'Sach', 'Loliyekar', '15'],
 ['2016-05-09', '9688156631', 'Saha', 'Oak', '22'],
 ['2016-05-09', '9895408016', 'Muku', 'Krishna', '23'],
 ['2016-05-09', '9261697610', 'Niloufe', 'Handa', '13'],
 ['2016-05-09', '9927277067', 'Ranja', 'Khare', '17'],
 ['2016-05-09', '9640338121', 'Brahm', 'Swamy', '23'],
 ['2016-05-09', '9485132704', 'Sohali', 'Das', '25'],
 ['2016-05-09', '9330107696', 'Nip', 'Naidu', '24'],
 ['2016-05-09', '9389644210', 'Brahm', 'Swamy', '18'],
 ['2016-05-09', '9389644210', 'Brahm', 'Swamy', '21']]

In [46]:
# 1.How many orders did the site receive?

print(len(ctmdata))

159

In [48]:
# 2.What was the total amount of the orders?
sum = 0
for i in ctmdata:
    sum += int(i[4])
print(sum)

2779

In [55]:
# 3.List the names of the customers who ordered once and did not order again.
dir = {}
for i in ctmdata:
    if i[2]+' '+i[3] not in dir:
        dir[i[2]+' '+i[3]] = 0
    else:
        dir[i[2]+' '+i[3]] = int(dir[i[2]+' '+i[3]]) +1
users = []
for j in dir:
    if dir[j]==0:
        users.append(j)
print(users)

['Dhenuk Dhawan',
 'Salmali Mehta',
 'Atma Mathur',
 'Gaur Som',
 'Nira Khalsa',
 'Adr Dave',
 'Hasti Mangal',
 'Ballar Upadhyay',
 'Mitr Gounder',
 'Niloufe Handa',
 'Sohali Das']

In [82]:
# 4.Get a distribution of customers who ordered exactly once, exactly twice, and so on up to 4 orders and group the rest as 5 orders and abo
cnt_stats = [0]*5
for j in dir:
    if dir[j]>=5:
        cnt_stats[4] += 1
    elif dir[j]==4:
        cnt_stats[3] += 1
    elif dir[j]==3:
        cnt_stats[2] += 1
    elif dir[j]==2:
        cnt_stats[1] += 1
    elif dir[j]==1:
        cnt_stats[0] += 1
fin = [['No. of orders','Count of customers']]
for i in range(0,5):
    if i==4:
        fin.append([str(str(i+1)+'+'),cnt_stats[i]])
    else:
        fin.append([i+1,cnt_stats[i]])
fin

[['No. of orders', 'Count of customers'],
 [1, 9],
 [2, 10],
 [3, 9],
 [4, 4],
 ['5+', 3]]

In [84]:
# 5.Generate this report as a simple HTML page with a table.
# 6.Add a bar graph for the information in Q4 in your HTML report.

report = open("report.html","w")
rpt_data = '''<html>
            <head>
            <title>customer data report</title>
            <script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
            <script type="text/javascript">
                      window.onload = function () {
                        var chart = new CanvasJS.Chart("stats",
                        {
                          title:{
                            text: "bar graph for the information in Q4 in your HTML report."
                          },
                          data: [
                          {
                            type: "bar",
                            dataPoints: [
                            { y: 9, label: "1"},
                            { y: 10, label: "2"},
                            { y:9, label: "3"},
                            { y: 4, label: "4"},
                            { y:3, label: "5"},

                            ]
                          },
                          ]
                        });

                    chart.render();
                    }
            </script>
            </head>
            <body>
            <table>
            <tr>
            <th>1.Total Orders site received</<th>
            <th>2.Total amount of orders site receive</<th>
            <th>3.customers who ordered only once</<th>
            <th>4.Distribution of customers based on orders</<th>
            <th></<th>
            </tr>
            <tr>
            <td>159</td>
            <td>2779</td>
            <td>'Salmali Mehta',
             'Atma Mathur',
             'Gaur Som',
             'Nira Khalsa',
             'Adr Dave',
             'Hasti Mangal',
             'Ballar Upadhyay',
             'Mitr Gounder',
             'Niloufe Handa',
             'Sohali Das'</td>
            <td>[['No. of orders', 'Count of customers'],
                 [1, 9],
                 [2, 10],
                 [3, 9],
                 [4, 4],
                 [5, 3]]</td>
            </tr>
            </table>
            <br>
            <div>bar graph for the information in Q4 in your HTML report.</div>
            <div id="stats"></div>
                
            </body></html>'''
            
report.write(rpt_data)   
report.close()